## 1. How likely is it that you roll doubles when rolling two dice?

In [7]:
import numpy as np
import pandas as pd

np.random.seed(29)

In [353]:
n_trials = nrows = 10_000
n_dice = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[2, 4],
       [2, 1],
       [3, 2],
       ...,
       [4, 5],
       [2, 5],
       [6, 4]])

In [354]:
df = pd.DataFrame(rolls, columns=['Die 1', 'Die 2'])
df.head()

Die 1  Die 2
0      2      4
1      2      1
2      3      2
3      3      2
4      4      6

In [355]:
df['Doubles'] = df['Die 1'] == df['Die 2']
df.head()

Die 1  Die 2  Doubles
0      2      4    False
1      2      1    False
2      3      2    False
3      3      2    False
4      4      6    False

In [356]:
probability_doubles = df['Doubles'].mean()
probability_doubles

0.1681

## 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?


In [36]:
n_trials = nrows = 10_000
n_coins = ncols = 8
outcomes = ['H','T']

In [38]:
eight_flips = np.random.choice(outcomes, (n_trials, n_coins))
eight_flips

array([['T', 'H', 'H', ..., 'T', 'H', 'H'],
       ['T', 'H', 'H', ..., 'T', 'H', 'T'],
       ['T', 'H', 'H', ..., 'T', 'H', 'H'],
       ...,
       ['T', 'T', 'T', ..., 'T', 'T', 'T'],
       ['T', 'H', 'H', ..., 'T', 'T', 'T'],
       ['H', 'H', 'T', ..., 'H', 'H', 'T']], dtype='<U1')

In [39]:
(eight_flips == 'H').sum(axis=1)

array([5, 4, 5, ..., 1, 4, 4])

In [43]:
prob_exactly_3_heads = ((eight_flips == 'H').sum(axis=1) == 3).mean()
prob_exactly_3_heads

0.2138

In [48]:
prob_more_than_3_heads = ((eight_flips == 'H').sum(axis=1) > 3).mean()
prob_more_than_3_heads

0.6394

## 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [345]:
prob = 1/4
drive_by = 2
trials_drive = 10_000
bb_array = np.random.random((trials_drive, drive_by))
bb_array



array([[0.35448399, 0.0657788 ],
       [0.84608653, 0.88602877],
       [0.397946  , 0.42602397],
       ...,
       [0.07792842, 0.72302844],
       [0.0385882 , 0.18520685],
       [0.23390585, 0.87591882]])

In [350]:
((bb_array < prob).sum(axis=1)==2).mean()

0.0674

## 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [357]:
mean = 3
sd = 1.5
days = 5

In [361]:
daily_pt = (np.random.normal(mean,sd,(100_000,days)))
daily_pt

array([[ 4.95762516,  6.24958585,  3.69443366,  1.74897614,  1.22453691],
       [ 3.42744067,  3.81213992,  2.52169832,  5.71556321,  0.97925895],
       [ 2.23929988, -0.37200595,  4.28366067,  1.41012722,  4.43151107],
       ...,
       [ 2.4669206 ,  3.24326938,  2.99199687,  1.06913252,  4.08373547],
       [ 4.17015289,  2.69322437,  0.44955142,  2.92436046,  2.80559373],
       [ 6.45751547,  4.23746471,  3.5869221 ,  1.72265889,  3.67004826]])

In [364]:
weekly_pt = daily_pt.sum(axis=1)
weekly_pt

array([17.87515772, 16.45610107, 11.9925929 , ..., 13.85505484,
       13.04288287, 19.67460943])

In [366]:
(17 - weekly_pt) > 1

array([False, False,  True, ...,  True,  True, False])

In [367]:
((17 - weekly_pt) > 1).mean()

0.61891

## 5. Compare Heights 
    Men have an average height of 178 cm and standard deviation of 8cm.
    Women have a mean of 170, sd = 6cm.
    Since you have means and standard deviations, you can use np.random.normal to generate observations.
    - If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [368]:
m_ave = 178
m_std = 8
f_ave = 170
f_std = 6

In [369]:
random_male = np.random.normal(m_ave,m_std, 100_000)
random_male

array([170.10336685, 171.39668585, 171.07040416, ..., 182.82764759,
       167.39281367, 185.07905616])

In [370]:
random_female = np.random.normal(f_ave,f_std, 100_000)
random_female

array([165.69612826, 180.19162419, 174.29939781, ..., 167.50135297,
       166.28939627, 178.70646665])

In [371]:
prob_f_taller_than_m = (random_female > random_male).mean()
prob_f_taller_than_m

0.21137

## 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

In [133]:
odd_corrupt = 1/250
n_students = 450
n_trials = 100_000

In [134]:
data = np.random.random((n_trials,n_students))
data

array([[0.13401559, 0.46871057, 0.07796923, ..., 0.91514757, 0.5842561 ,
        0.85051672],
       [0.5962733 , 0.10398473, 0.53412493, ..., 0.08971387, 0.89192536,
        0.76869931],
       [0.83352809, 0.57995227, 0.84884585, ..., 0.01161674, 0.51303293,
        0.03036368],
       ...,
       [0.0313857 , 0.86647283, 0.99892272, ..., 0.25205634, 0.79752604,
        0.88579132],
       [0.90891612, 0.41266799, 0.50999889, ..., 0.2414604 , 0.39576355,
        0.54154739],
       [0.23892699, 0.49347844, 0.05133928, ..., 0.79074889, 0.21119304,
        0.68950439]])

In [135]:
(data < odd_corrupt) #are any less than odds

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [136]:
(data < odd_corrupt).sum(axis=1) #sum of T or F

array([2, 4, 0, ..., 1, 3, 2])

In [115]:
(data < odd_corrupt).sum(axis=1) == 0 #True if no corrupt

array([False,  True, False, ...,  True,  True,  True])

In [116]:
((data < odd_corrupt).sum(axis=1) == 0).mean() #odds no corrupt w/ 50 students

0.81632

In [121]:
((data < odd_corrupt).sum(axis=1) == 0).mean() #odds no corrupt w/ 100 students

0.66889

### What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [131]:
(data < odd_corrupt).sum(axis=1) != 0 #True if any corrupt

array([False, False,  True, ...,  True, False,  True])

In [132]:
((data < odd_corrupt).sum(axis=1) != 0).mean() #odds we observe install issue within first 150 students

0.45269

### How likely is it that 450 students all download anaconda without an issue?

In [137]:
(data < odd_corrupt).sum(axis=1) == 0 #True if no corrupt

array([False, False,  True, ..., False, False, False])

In [138]:
((data < odd_corrupt).sum(axis=1) == 0).mean() #odds 450 students download without issue

0.16487

## 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [139]:
ft_odds = .7
ft_days = 3
ft_trials = 100_000

In [141]:
ft_data = np.random.random((ft_trials, ft_days))
ft_data

array([[0.19134616, 0.84138674, 0.96285398],
       [0.24176763, 0.94916583, 0.23166545],
       [0.03458824, 0.45457025, 0.11076582],
       ...,
       [0.60862598, 0.22580738, 0.61508084],
       [0.95940878, 0.26278479, 0.16335598],
       [0.65124831, 0.79558849, 0.36540874]])

In [142]:
ft_data > ft_odds #True = no food truck

array([[False,  True,  True],
       [False,  True, False],
       [False, False, False],
       ...,
       [False, False, False],
       [ True, False, False],
       [False,  True, False]])

In [143]:
(ft_data > ft_odds).sum(axis=1) #3 = no food truck 3 days in a row

array([2, 1, 0, ..., 0, 1, 1])

In [159]:
((ft_data > ft_odds).sum(axis=1)==3).mean() #odds no food truck 3 days in a row

0.02746

### How likely is it that a food truck will show up sometime this week?

In [146]:
ft_odds = .7
ft_wk = 7
ft_trials = 100_000

In [147]:
ft_wk_data = np.random.random((ft_trials, ft_wk))
ft_wk_data

array([[0.25524183, 0.87764945, 0.36911497, ..., 0.73586434, 0.13161981,
        0.847535  ],
       [0.21276934, 0.29595938, 0.21703163, ..., 0.97847684, 0.54791608,
        0.86267875],
       [0.29861157, 0.21623033, 0.55186041, ..., 0.75637867, 0.31032589,
        0.55221278],
       ...,
       [0.48793843, 0.04247324, 0.46433399, ..., 0.09149326, 0.28740085,
        0.45890244],
       [0.69197166, 0.6903685 , 0.53754282, ..., 0.38092965, 0.66424569,
        0.69494698],
       [0.07180327, 0.42393757, 0.72078297, ..., 0.67811774, 0.30822868,
        0.42083724]])

In [152]:
ft_wk_data < ft_odds #False = no food truck

array([[ True, False,  True, ..., False,  True, False],
       [ True,  True,  True, ..., False,  True, False],
       [ True,  True,  True, ..., False,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True, False, ...,  True,  True,  True]])

In [153]:
(ft_wk_data < ft_odds).sum(axis=1)

array([4, 4, 6, ..., 7, 6, 6])

In [155]:
((ft_wk_data < ft_odds).sum(axis=1)>0).mean() #odds that a food truck came at least once

0.9998

## If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [374]:
bday_list = list(range(1,366,1))
bday_trials = 100_000
bday_n_ppl = 40
bday_array = np.random.choice(bday_list,(bday_trials, bday_n_ppl))
bday_array

array([[102, 264, 168, ..., 282, 193, 347],
       [174,   7, 204, ..., 182, 237, 306],
       [286,  57, 237, ..., 264, 218, 322],
       ...,
       [312,  13,  33, ...,  83,  39, 167],
       [330, 271, 158, ..., 114, 167, 116],
       [130, 220, 175, ..., 157,  20, 168]])

In [375]:
bday_df = pd.DataFrame(bday_array)
bday_df.iloc[1]

0     174
1       7
2     204
3      51
4     205
5     131
6      60
7      61
8      35
9     271
10    110
11    179
12    134
13    123
14    174
15    138
16    283
17     60
18     88
19    127
20     81
21     17
22     41
23    171
24    354
25    112
26    164
27    273
28    350
29    111
30     86
31    235
32    300
33     83
34     82
35     28
36    240
37    182
38    237
39    306
Name: 1, dtype: int64

In [259]:
for n in bday_df.iloc[0]:
    print(n)

13
62
203
84
98
327
76
124
67
219
363
309
245
278
103
120
203
249
310
142
16
171
164


In [265]:
bday_df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [316]:
bday_df

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0      70  283  129  165   98   15  163  178  360   46  ...  203   13  305   
1      27  256  298  333  195  187  268   60  129  209  ...  317  119  275   
2     133   54  120  231  294  108  196  349  175  149  ...  175   37  186   
3     300  181    7   19  230   67   89    8  355  303  ...  239  295  342   
4      75  270  278  143  358  305  309  237   35  329  ...  294  225   67   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995   34  133  256  114   38  208  356  106  288  249  ...   84  281   55   
9996  244  106  274  110  175    3  118  188  305  343  ...  359  359  325   
9997  178  214  307  180  259   46  341  328   19  348  ...  293  268   67   
9998  152   35   27  124  268  198  324  121  222   36  ...   73  127  140   
9999  205  247   91  326  148  333  160  162  192  220  ...  317   87   93   

       16   17   18   19   20   21   22  
0     277  169   29   22  358  365  340  
1     259   33  183  228   13   76  190  
2     297  117  258  106  239    8    5  
3     251  314  200  343  179  163  214  
4     349  187  141  279   74   71   82  
...   ...  ...  ...  ...  ...  ...  ...  
9995  332  181  162  181  322  199  209  
9996  278  236  356  230  118   41  350  
9997   39  311  251  150  159  347  127  
9998  159  293  222  250  301  272   60  
9999  149  227  348   12  355  100  334  

[10000 rows x 23 columns]

In [372]:
bday_df.nunique(axis=1)

0        23
1        22
2        22
3        22
4        22
         ..
99995    22
99996    23
99997    23
99998    22
99999    23
Length: 100000, dtype: int64

In [373]:
(bday_df.nunique(axis=1) != 23).mean() #23 people

0.50489

In [339]:
(bday_df.nunique(axis=1) != 20).mean() #20 people

0.41147

In [376]:
(bday_df.nunique(axis=1) != 40).mean() #40 people

0.89171